<a href="https://colab.research.google.com/github/it2Vishal/Vishal_leetcode/blob/main/Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [50]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)


[5 7 9]


In [4]:
print(a-b)

[-3 -3 -3]


In [5]:
print(a*b)

[ 4 10 18]


In [6]:
print(a/b)

[0.25 0.4  0.5 ]


In [8]:
print(a**3) #exponent
print(b**3)

[ 1  8 27]
[ 64 125 216]


In [9]:
print(np.sqrt(a)) # To find the sq root

[1.         1.41421356 1.73205081]


In [10]:
print(np.power(a,5)) # For n exponent

[  1  32 243]


In [23]:
print(np.array([10,20,30,40,50])) #array fefining 2d array

[10 20 30 40 50]


In [19]:
print(np.mean(arr))

30.0


In [24]:
print(np.var(arr))

200.0


In [25]:
print(np.std(arr))

14.142135623730951


In [26]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [28]:
arr = np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


In [33]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [34]:
import numpy as np

In [35]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.arange(1,11) # array in particulalar range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
np.random.rand(5) # given random number below 1

array([0.07352914, 0.49568206, 0.24137123, 0.04642357, 0.18195394])

In [45]:
np.random.randint(1,100,11)

array([93,  3, 52, 19, 96, 93, 96, 35,  7, 27, 13])

In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [53]:
arr = np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [ ]:
arr = np.array[1,2,3,4,5,6]
